spring.application.name=SMS109
spring.datasource.url=jdbc:mysql://localhost:3306/SMS109
spring.datasource.username=root
spring.datasource.password=Yaswanth2203$
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
